# Generated by Django 4.1.2 on 2022-11-04 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(editable=False, max_length=10)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('number_of_lessons', models.PositiveIntegerField(choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes')])),
                ('interval_between_lessons', models.PositiveIntegerField(choices=[(1, '1 Week'), (2, '2 Weeks')])),
                ('duration_of_lessons', models.PositiveIntegerField(choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes')])),
                ('further_information', models.CharField(max_length=500)),
                ('availability', models.ManyToManyField(to='lessons.dayoftheweek')),
            ],
        ),
    ]
