# Generated by Django 4.1.3 on 2022-12-04 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='interval_between_lessons',
            field=models.PositiveIntegerField(choices=[(7, '1 Week'), (14, '2 Weeks')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval_between_lessons',
            field=models.PositiveIntegerField(choices=[(7, '1 Week'), (14, '2 Weeks')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_lessons',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9223372036854775807)]),
        ),
    ]
