# Generated by Django 4.1.3 on 2022-11-10 18:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today, message='')]),
        ),
    ]
