# Generated by Django 4.1.3 on 2022-12-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='term',
            new_name='term_id',
        ),
    ]
