# Generated by Django 4.1.3 on 2022-11-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day_of_the_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.dayoftheweek'),
        ),
    ]
