# Generated by Django 4.1.3 on 2022-11-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='student_name',
            field=models.CharField(default='fnln', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='student_name',
            field=models.CharField(default='fnln', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='fnln', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student')),
            ],
        ),
    ]
