# Generated by Django 4.1.3 on 2022-11-12 01:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_banktransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now, message='')]),
        ),
    ]
