# Generated by Django 4.1.3 on 2022-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_booking_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day_of_the_week',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
