# Generated by Django 4.1.3 on 2022-11-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_child_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
