# Generated by Django 4.1.3 on 2022-11-21 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_booking_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Invoice number must follow the format xxxx-yyy where x is the student number and y is the invoice number.', regex='^\\d{4}-\\d{3}$')]),
        ),
    ]
