# Generated by Django 4.1.3 on 2022-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='last_name',
        ),
        migrations.AddField(
            model_name='child',
            name='full_name',
            field=models.CharField(default='You', max_length=100),
            preserve_default=False,
        ),
    ]
