# Generated by Django 4.1.3 on 2022-11-21 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_request_number_of_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Invoice number must follow the format xxxx-yyy where x is the student number and y is the invoice number.', regex='^\\d{4}-\\d{3}$')])),
                ('full_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('fully_paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student')),
            ],
        ),
    ]
