# Generated by Django 4.1.3 on 2022-11-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_request_date'),
        ('lessons', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
    ]
