# Generated by Django 4.1.3 on 2022-11-14 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_merge_20221114_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=10, unique=True)),
                ('day_of_the_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('time_of_the_day', models.TimeField()),
                ('teacher', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('duration_of_lessons', models.PositiveIntegerField(choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes')])),
                ('interval_between_lessons', models.PositiveIntegerField(choices=[(1, '1 Week'), (2, '2 Weeks')])),
                ('number_of_lessons', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('further_information', models.CharField(max_length=500)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
