# Generated by Django 4.1.3 on 2022-11-15 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lessons.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_booking_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_record', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('lessons.user',),
            managers=[
                ('objects', lessons.user_manager.UserManager()),
            ],
        ),
    ]
