# Generated by Django 4.1.3 on 2022-11-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
